article_module/urls.py
from django.urls import path

from home_module.views import HomePageView
from .views import *
urlpatterns = [
    path('', body_main_sideView.as_view(), name="home-page"),
    path('articles', RedirectHome.as_view(), name="redirect-home_articles"),
    path('articles/cat', RedirectHome.as_view(), name="redirect-home_cat"),
    path('articles/cat/zommit', RedirectHome.as_view(), name="redirect-home_zommit"),
    path("articles/cat/<str:category>", body_main_sideView.as_view(), name="home-page-by-category"),
    path("articles/<slug:slug>", detailPageView.as_view(), name="detail-page"),
]

home_module/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("contact-us", ConatctUsView.as_view(), name="contactUs-page")
]

zommitwebapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article_module.urls')),
    path('', include('home_module.urls')),
    path('account/', include('account_module.urls')),

]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article_module/models.py
from django.db import models

# Create your models here.
from account_module.models import User


class ArticleCategory(models.Model):
    parent = models.ForeignKey("ArticleCategory",null=True,blank=True,on_delete=models.CASCADE ,verbose_name="دسته بندی")
    title = models.CharField(max_length=200, verbose_name="عنوان دسته بندی")
    url_title = models.CharField(max_length=200,unique=True, verbose_name="عنوان  دسته بندی در url")
    is_active = models.BooleanField(default=True, verbose_name="فعال / غیرفعال")
    is_article = models.BooleanField(default=True, verbose_name="مقاله میباشد")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "دسته بندی مقالات"
        verbose_name_plural = "دسته بندی های مقالات"

class Article(models.Model):
    title = models.CharField(max_length=300, verbose_name="عنوان مقاله")
    slug = models.SlugField(max_length=400, allow_unicode=True, db_index=True, verbose_name="عنوان در url")
    image = models.ImageField(upload_to="images/articles", verbose_name="تصویر مقاله")
    short_description = models.TextField(verbose_name="توضحیات مختصر")
    text = models.TextField(verbose_name="توضیحات مقاله")
    is_active = models.BooleanField(default=True, verbose_name="فعال / غیرفعال")
    selected_categories = models.ManyToManyField(to="ArticleCategory", verbose_name="دسته بندی های مقاله")
    author = models.ForeignKey(User, verbose_name="نویسنده", null=True, editable=False, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد", editable=False)
    view_count = models.IntegerField(default=0, verbose_name="تعداد بازدید")
    is_suggest = models.BooleanField(default=False, verbose_name="پیشنهاد سردبیر")
    is_slider = models.BooleanField(default=False, verbose_name="نمایش در اسلایدر")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"

article_module/views.py
from django.http import HttpRequest
from django.shortcuts import render,redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView,DetailView
from django.views.generic.base import TemplateView
from .models import Article, ArticleCategory
# Create your views here.
from home_module.views import HomePageView

class RedirectHome(View):
    def get(self, request):
        return redirect(reverse("home-page"))

class body_main_sideView(ListView):
    model = Article
    template_name = "article_module/body_components/homePage/main_side-home.html"
    paginate_by = 8

    def get_queryset(self):
        query = super(body_main_sideView, self).get_queryset()
        query = query.order_by("-create_date")
        category_name = self.kwargs.get("category")
        if(category_name is not None):
            query = query.filter(selected_categories__url_title__iexact=category_name, is_active=True)
        return query

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(body_main_sideView, self).get_context_data()
        url_title = self.kwargs.get("category", None)
        if(url_title):
            title = ArticleCategory.objects.filter(url_title=url_title).values("title")[0].get("title")
            context["url_persian_title"] = title
        return context

class detailPageView(DetailView):
    model = Article
    template_name = "article_module/body_components/detailPage/main_side-details.html"


class body_right_sideView(ListView):
    # most-view articles
    model = Article
    template_name = "article_module/body_components/homePage/right_side.html"

    def get_queryset(self):
        query = super(body_right_sideView, self).get_queryset()
        query = query.order_by("-view_count")[:5]
        return query

class body_left_sideView(ListView):
    model = Article
    template_name = "article_module/body_components/homePage/left_side.html"
    
    def get_queryset(self):
        query = super(body_left_sideView, self).get_queryset()
        query = query.filter(selected_categories__url_title__iexact="howto")[:5]
        return query



def header_main_menuView(request:HttpRequest):
    article_main_categories = ArticleCategory.objects.filter(is_active=True, parent_id=None)
    context = {
        "main_categories": article_main_categories
    }
    return render(request, "article_module/header_components/main-menu.html", context)

article_module/templates/article_module/header_components/main-menu.html
{% load static %}
<!-- /---main menu on lg and bigger---/ -->
<nav id="mainMenu" class="main-lg w-100" style="z-index:1000;">
    <div class="container">
        <ul class="d-none d-lg-flex flex-row-reverse">
            <li class="px-lg-2 px-md-1 py-4">
                <a href="{% url 'home-page' %}">
                    <img id="brand" src="{% static 'imgs/logo/zoomit_logo_h.svg' %}" alt="">
                </a>
            </li>
            <li class="px-lg-2 py-4">
                <a href="{% url 'home-page' %}">
                    <i class=""></i>
                    محصولات
                </a>
            </li>
            {% for main_cat in main_categories %}
                {% if main_cat.articlecategory_set.all %}
            <li class="main-subMegaMenu px-lg-2 py-4 position-relative">
                <a href="{% url 'home-page-by-category' category=main_cat.url_title %}">
                    <i class="fa fa-caret-down"></i>
                    {{ main_cat.title }}
                </a>
                <ul id="main-megaMenu" class="d-none d-lg-none flex-column position-absolute pe-4 py-3 ps-3">
                    {% for sub_cat in main_cat.articlecategory_set.all %}
                    <li class="p-1">
                    {% if sub_cat.is_article %}
                        <a href="{% url 'home-page-by-category' category=sub_cat.url_title %}">
                            {{ sub_cat.title }}
                        </a>
                    {% else %}
                        <a href="{% url 'home-page' %}{{ sub_cat.url_title }}">
                            {{ sub_cat.title }}
                        </a>
                    {% endif %}
                    </li>
                    {% endfor %}
                </ul>
            </li>
                {% else %}
            <li class="main-subMegaMenu px-lg-2 py-4">
                <a href="{% url 'home-page-by-category' category=main_cat.url_title %}" >
                    {{ main_cat.title }}
                </a>
            </li>
                 {% endif %}
            {% endfor %}

            {% if not request.user.is_authenticated %}
                <li id="nav-ico1" class="me-auto px-lg-2 py-4">
                    <a href="{% url 'register_page' %}">
                        <i class="fa fa-user" style="font-size:24px"></i>
                    </a>
                </li>
                <li id="nav-ico2" class="px-lg-2 py-4">
                    <a href="#">
                        <i class="fa fa-share-alt" style="font-size:24px"></i>
                    </a>
                </li>
                <li id="anv-ico3" class="px-lg-2 py-4">
                    <a href="#">
                        <i class="fa fa-search" style="font-size:24px"></i>
                    </a>
                </li>
            {% else %}
                <li id="anv-ico4" class="me-auto px-lg-2 py-4">
                <a href="#">
                    <span>{{ request.user.username }}</span>کاربر
                    <i class="fa fa-user" style="font-size:24px"></i>
                </a>
                </li>
                <li id="anv-ico3" class="px-lg-2 py-4">
                    <a href="{% url 'logout_page' %}">
                    <span>خروج</span>
                    </a>
                </li>
            {% endif %}

        </ul>
    </div>
</nav>




<!-- /---main menu on md and smaller---/ -->
<div id="mainMenu">
    <div class="container-fluid">
        <div class="d-flex d-lg-none flex-row-reverse justify-content-between">
            <a id="navIco" class="py-3" href="#">
                <i class="fa fa-navicon" style="font-size:24px"></i>
            </a>
            <a class="py-3" href="{% url 'home-page' %}">
                <img id="brand" src="{% static 'imgs/logo/zoomit_logo_h.svg' %}" alt="">
            </a>
            <a class="py-3" href="#">
                <i class="fa fa-search" style="font-size:24px"></i>
            </a>
        </div>
    </div>
</div>
<!-- /---main menu list on md and smaller---/ -->
<div id="menuList">
    <div class="container-fluid">
        <ul id="menuList-ul" class="d-none d-lg-none flex-column" style="text-align:right;">
            <li class="subMegaMenu">
                <a class="p-3 d-flex justify-content-between align-items-center" href="{% url 'home-page' %}">
                    <i class="" style="font-size:12px"></i>
                    محصولات
                </a>
            </li>
            {% for main_cat in main_categories %}
                {% if main_cat.articlecategory_set.all %}
                <li class="subMegaMenu">
                <a class="p-3 d-flex justify-content-between align-items-center" href="#">
                    <i class="fa fa-caret-left" style="font-size:12px"></i>
                    {{ main_cat.title }}
                </a>
                <!-- /---li megaMenu---/ -->
                <ul id="megaMenu" class="d-none d-lg-none flex-column position-absolute w-100">
                    {% for sub_cat in main_cat.articlecategory_set.all %}
                    <li class="p-3">
                    {% if sub_cat.is_article %}
                        <a href="{% url 'home-page-by-category' category=sub_cat.url_title %}">
                            {{ sub_cat.title }}
                        </a>
                    {% else %}
                        <a href="{% url 'home-page' %}{{ sub_cat.url_title }}">
                            {{ sub_cat.title }}
                        </a>
                    {% endif %}
                    </li>
                    {% endfor %}
                </ul>
            </li>
                {% else %}
                <li class="subMegaMenu">
                <a class="p-3 d-flex justify-content-between align-items-center" href="#">
                    <i class="fa" style="font-size:12px"></i>
                    {{ main_cat.title }}
                </a>
            </li>
                {% endif %}
            {% endfor %}


            <li id="login-register" class="subMegaMenu">
                <a class="p-3 d-flex justify-content-end" href="{% url 'register_page' %}">
                    ورود | عضویت
                    <i class="ms-2 fa fa-user-o" style="font-size:20px"></i>
                </a>
            </li>
            <li id="social-icons" class="subMegaMenu">
                <div id="wrapper" class="d-flex flex-row-reverse" href="#">
                    <a href="#">
                        <i class="fa fa-telegram"></i>
                    </a>
                    <a href="#">
                        <i class="fa fa-instagram"></i>
                    </a>
                    <a href="#">
                        <i class="fa fa-twitter"></i>
                    </a>
                    <a href="#">
                        <i class="fa fa-youtube-play"></i>
                    </a>
                </div>
            </li>
        </ul>
    </div>
</div>