article_module/urls.py
from django.urls import path

from home_module.views import HomePageView
from .views import *
urlpatterns = [
    path('', body_main_sideView.as_view(), name="home-page"),
    path('articles', RedirectHome.as_view(), name="redirect-home_articles"),
    path('articles/cat', RedirectHome.as_view(), name="redirect-home_cat"),
    path('articles/cat/zommit', RedirectHome.as_view(), name="redirect-home_zommit"),
    path("articles/cat/<str:category>", body_main_sideView.as_view(), name="home-page-by-category"),
    path("articles/<slug:slug>", detailPageView.as_view(), name="detail-page"),
]

home_module/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("contact-us", ConatctUsView.as_view(), name="contactUs-page")
]

zommitwebapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('article_module.urls')),
    path('', include('home_module.urls')),
    path('account/', include('account_module.urls')),

]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article_module/models.py
from django.db import models

# Create your models here.
from account_module.models import User


class ArticleCategory(models.Model):
    parent = models.ForeignKey("ArticleCategory",null=True,blank=True,on_delete=models.CASCADE ,verbose_name="دسته بندی")
    title = models.CharField(max_length=200, verbose_name="عنوان دسته بندی")
    url_title = models.CharField(max_length=200,unique=True, verbose_name="عنوان  دسته بندی در url")
    is_active = models.BooleanField(default=True, verbose_name="فعال / غیرفعال")
    is_article = models.BooleanField(default=True, verbose_name="مقاله میباشد")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "دسته بندی مقالات"
        verbose_name_plural = "دسته بندی های مقالات"

class Article(models.Model):
    title = models.CharField(max_length=300, verbose_name="عنوان مقاله")
    slug = models.SlugField(max_length=400, allow_unicode=True, db_index=True, verbose_name="عنوان در url")
    image = models.ImageField(upload_to="images/articles", verbose_name="تصویر مقاله")
    short_description = models.TextField(verbose_name="توضحیات مختصر")
    text = models.TextField(verbose_name="توضیحات مقاله")
    is_active = models.BooleanField(default=True, verbose_name="فعال / غیرفعال")
    selected_categories = models.ManyToManyField(to="ArticleCategory", verbose_name="دسته بندی های مقاله")
    author = models.ForeignKey(User, verbose_name="نویسنده", null=True, editable=False, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد", editable=False)
    view_count = models.IntegerField(default=0, verbose_name="تعداد بازدید")
    is_suggest = models.BooleanField(default=False, verbose_name="پیشنهاد سردبیر")
    is_slider = models.BooleanField(default=False, verbose_name="نمایش در اسلایدر")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"

article_module/views.py
from django.http import HttpRequest
from django.shortcuts import render,redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView,DetailView
from django.views.generic.base import TemplateView
from .models import Article, ArticleCategory
# Create your views here.
from home_module.views import HomePageView

class RedirectHome(View):
    def get(self, request):
        return redirect(reverse("home-page"))

class body_main_sideView(ListView):
    model = Article
    template_name = "article_module/body_components/homePage/main_side-home.html"
    paginate_by = 8

    def get_queryset(self):
        query = super(body_main_sideView, self).get_queryset()
        query = query.order_by("-create_date")
        category_name = self.kwargs.get("category")
        if(category_name is not None):
            query = query.filter(selected_categories__url_title__iexact=category_name, is_active=True)
        return query

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(body_main_sideView, self).get_context_data()
        url_title = self.kwargs.get("category", None)
        if(url_title):
            title = ArticleCategory.objects.filter(url_title=url_title).values("title")[0].get("title")
            context["url_persian_title"] = title
        return context

class detailPageView(DetailView):
    model = Article
    template_name = "article_module/body_components/detailPage/main_side-details.html"


class body_right_sideView(ListView):
    # most-view articles
    model = Article
    template_name = "article_module/body_components/homePage/right_side.html"

    def get_queryset(self):
        query = super(body_right_sideView, self).get_queryset()
        query = query.order_by("-view_count")[:5]
        return query

class body_left_sideView(ListView):
    model = Article
    template_name = "article_module/body_components/homePage/left_side.html"
    
    def get_queryset(self):
        query = super(body_left_sideView, self).get_queryset()
        query = query.filter(selected_categories__url_title__iexact="howto")[:5]
        return query



def header_main_menuView(request:HttpRequest):
    article_main_categories = ArticleCategory.objects.filter(is_active=True, parent_id=None)
    context = {
        "main_categories": article_main_categories
    }
    return render(request, "article_module/header_components/main-menu.html", context)

article_module/templates/article_module/body_components/homePage/left_side.html
<div id="left-side" class="d-none d-lg-flex col-lg-3 flex-column align-items-end">
            <!-- title -->
            <div class="card w-100">
                <div id="side-header" class="p-2 col-12">
                    آموزش
                </div>
            </div>
            <!-- posts -->
            {% for article in article_list %}
            <div class="card px-2 py-3">
                <div class="row g-0">
                    <div class="col-4 d-flex align-items-center p-0">
                        <a href="{% url 'detail-page' slug=article.slug %}">
                            <img style="height:100% ;" src="{{ article.image.url }}" class="img-fluid" alt="...">
                        </a>
                    </div>
                    <div class="col-8">
                        <div class="card-body p-1">
                            <a href="{% url 'detail-page' slug=article.slug %}">
                                <p class="card-text">{{ article.title }}</p>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>

article_module/templates/article_module/body_components/homePage/main_side-home.html
{#--homePage--#}
{% extends "home_module/homePage.html" %}
{% load jalali_tags %}

{% block title %}
    {% if request.path == "/" %}
        صفحه اصلی
        {% else %}
        {{ url_persian_title }}
    {% endif %}
{% endblock %}

{% block main-side %}
<div id="main-side" class="col-md-9 col-lg-6">
                <!-- title -->
                <div class="card">
                    <div id="side-header" class="p-2 col-12">
                    {% if request.path == "/" %}
                        مطالب جدید
                        {% else %}
                           مطالب بخش
                        {{ url_persian_title }}
                    {% endif %}
                    </div>
                </div>
                <!-- posts -->
                {% for article in article_list %}
                    <div class="card px-2 py-3">
                    <div class="row g-0">
                        <div class="col-4 p-0">
                            <a href="{% url 'detail-page' slug=article.slug %}">
                                <img src="{{ article.image.url }}" class="img-fluid" alt="...">
                            </a>
                        </div>
                        <div class="col-8">
                            <div class="card-body p-2 pe-3">
                                <div style="display: flex;flex-direction: row">
                                    {% for cat in article.selected_categories.all %}
                                        <a href="{% url 'home-page-by-category' category=cat.url_title %}">
                                        {% if article.selected_categories.last == cat %}
                                            <h6 class="card-subtitle text-muted"> {{ cat.title }} </h6>
                                            {% else %}
                                            <h6 class="card-subtitle text-muted"> {{ cat.title }} , </h6>
                                        {% endif %}
                                        </a>
                                        {% endfor %}
                                </div>
                                <a href="{% url 'detail-page' slug=article.slug %}">
                                    <h5 class="py-2 card-title">
                                        {{ article.title }}
                                    </h5>
                                </a>
                                <a href="#">
                                    <h6 class="card-author" style="font-family: IranSans">
{#                                        {{article.author}} | ۰۹:۴۵ ۱۴۰۱/۰۵/۱۹ | + دیدگاه#}
                                        {{article.author}} | {{ article.create_date | to_jalali}}  | + دیدگاه
                                    </h6>
                                </a>
                                <a href="{% url 'detail-page' slug=article.slug %}">
                                    <p class="py-2 card-text">
                                        {{ article.short_description }}
                                    </p>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}

                <nav aria-label="Page navigation example">
                  <ul class="pagination justify-content-end">
                      {% if page_obj.has_previous %}
                          <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">قبلی</a>
                          </li>
                      {% endif %}

                    {% for pageNum in paginator.page_range %}
                        <li class="page-item"><a class="page-link" href="?page={{ pageNum }}">{{ pageNum }}</a></li>
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{ page_obj.next_page_number }}">بعدی</a>
                    </li>
                  {% endif %}
                  </ul>
                </nav>

            </div>
{% endblock %}

article_module/templates/article_module/body_components/homePage/right_side.html
<div id="right-side" class="d-none d-md-flex col-md-3 col-lg-3 flex-column">
            <!-- title -->
            <div class="card">
                <div id="side-header" class="p-2 col-12">
                    پربازدیدترین مطالب
                </div>
            </div>
            <!-- posts -->
            {% for article in article_list %}
            <div class="card mb-2">
                <a href="#">
                    <img src="{{ article.image.url }}" class="card-img-top" alt="{{ article.title }}">
                </a>
                <div class="card-body">
                    <a href="">
                        <p class="card-text">{{ article.title }}</p>
                    </a>
                </div>
            </div>
            {% endfor %}
            </div>